name: Test action
on:
  workflow_dispatch:

env:
  mnbenefits_env_url: any_string_works_for_github_tests

jobs:
  full-flow-journey-test:
    name: Run full flow journey test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2.3.0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Get IPv4 Address
        run: |
          curl ifconfig.me        
      - name: Test with Gradle
        run: ./gradlew fullFlowJourneyTest
      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
